screen -dmS putOnServers-b01 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers1.txt;"
screen -dmS putOnServers-b02 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers2.txt;"
screen -dmS putOnServers-b03 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers3.txt;"
screen -dmS putOnServers-b04 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers4.txt;"
screen -dmS putOnServers-b05 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers5.txt;"
screen -dmS putOnServers-b06 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers6.txt;"
screen -dmS putOnServers-b07 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers7.txt;"
screen -dmS putOnServers-b08 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers8.txt;"
screen -dmS putOnServers-b09 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers9.txt;"
screen -dmS putOnServers-b10 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers10.txt;"
screen -dmS putOnServers-b11 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers11.txt;"
screen -dmS putOnServers-b12 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers12.txt;"
screen -dmS putOnServers-b13 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers13.txt;"
screen -dmS putOnServers-b14 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers14.txt;"
screen -dmS putOnServers-b15 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers15.txt;"
screen -dmS putOnServers-b16 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers16.txt;"
screen -dmS putOnServers-b17 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers17.txt;"
screen -dmS putOnServers-b18 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers18.txt;"
screen -dmS putOnServers-b19 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers19.txt;"
screen -dmS putOnServers-b20 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers20.txt;"
screen -dmS putOnServers-b21 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers21.txt;"
screen -dmS putOnServers-b22 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers22.txt;"
screen -dmS putOnServers-b23 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers23.txt;"
screen -dmS putOnServers-b24 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers24.txt;"
screen -dmS putOnServers-b25 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers25.txt;"
screen -dmS putOnServers-b26 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers26.txt;"
screen -dmS putOnServers-b27 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers27.txt;"
screen -dmS putOnServers-b28 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers28.txt;"
screen -dmS putOnServers-b29 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers29.txt;"
screen -dmS putOnServers-b30 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers30.txt;"
screen -dmS putOnServers-b31 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers31.txt;"
screen -dmS putOnServers-b32 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers32.txt;"
screen -dmS putOnServers-b33 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers33.txt;"
screen -dmS putOnServers-b34 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers34.txt;"
screen -dmS putOnServers-b35 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers35.txt;"
screen -dmS putOnServers-b36 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers36.txt;"
screen -dmS putOnServers-b37 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers37.txt;"
screen -dmS putOnServers-b38 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers38.txt;"
screen -dmS putOnServers-b39 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers39.txt;"
screen -dmS putOnServers-b40 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers40.txt;"
screen -dmS putOnServers-b41 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers41.txt;"
screen -dmS putOnServers-b42 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers42.txt;"
screen -dmS putOnServers-b43 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers43.txt;"
screen -dmS putOnServers-b44 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers44.txt;"
screen -dmS putOnServers-b45 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers45.txt;"
screen -dmS putOnServers-b46 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers46.txt;"
screen -dmS putOnServers-b47 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers47.txt;"
screen -dmS putOnServers-b48 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers48.txt;"
screen -dmS putOnServers-b49 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers49.txt;"
screen -dmS putOnServers-b50 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers50.txt;"
screen -dmS putOnServers-b51 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers51.txt;"
screen -dmS putOnServers-b52 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers52.txt;"
screen -dmS putOnServers-b53 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers53.txt;"
screen -dmS putOnServers-b54 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers54.txt;"
screen -dmS putOnServers-b55 bash -c "cd ~/vmscripts;./runOnServers.sh 1 servers/servers55.txt;"
screen -dmS putOnServers-b56 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers56.txt;'
screen -dmS putOnServers-b57 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers57.txt;'
screen -dmS putOnServers-b58 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers58.txt;'
screen -dmS putOnServers-b59 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers59.txt;'
screen -dmS putOnServers-b60 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers60.txt;'
screen -dmS putOnServers-b61 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers61.txt;'
screen -dmS putOnServers-b62 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers62.txt;'
screen -dmS putOnServers-b63 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers63.txt;'
screen -dmS putOnServers-b64 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers64.txt;'
screen -dmS putOnServers-b65 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers65.txt;'
screen -dmS putOnServers-b66 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers66.txt;'
screen -dmS putOnServers-b67 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers67.txt;'
screen -dmS putOnServers-b68 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers68.txt;'
screen -dmS putOnServers-b69 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers69.txt;'
screen -dmS putOnServers-b70 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers70.txt;'
screen -dmS putOnServers-b71 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers71.txt;'
screen -dmS putOnServers-b72 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers72.txt;'
screen -dmS putOnServers-b73 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers73.txt;'
screen -dmS putOnServers-b74 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers74.txt;'
screen -dmS putOnServers-b75 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers75.txt;'
screen -dmS putOnServers-b76 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers76.txt;'
screen -dmS putOnServers-b77 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers77.txt;'
screen -dmS putOnServers-b78 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers78.txt;'
screen -dmS putOnServers-b79 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers79.txt;'
screen -dmS putOnServers-b80 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers80.txt;'
screen -dmS putOnServers-b81 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers81.txt;'
screen -dmS putOnServers-b82 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers82.txt;'
screen -dmS putOnServers-b83 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers83.txt;'
screen -dmS putOnServers-b84 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers84.txt;'
screen -dmS putOnServers-b85 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers85.txt;'
screen -dmS putOnServers-b86 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers86.txt;'
screen -dmS putOnServers-b87 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers87.txt;'
screen -dmS putOnServers-b88 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers88.txt;'
screen -dmS putOnServers-b89 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers89.txt;'
screen -dmS putOnServers-b90 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers90.txt;'
screen -dmS putOnServers-b91 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers91.txt;'
screen -dmS putOnServers-b92 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers92.txt;'
screen -dmS putOnServers-b93 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers93.txt;'
screen -dmS putOnServers-b94 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers94.txt;'
screen -dmS putOnServers-b95 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers95.txt;'
screen -dmS putOnServers-b96 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers96.txt;'
screen -dmS putOnServers-b97 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers97.txt;'
screen -dmS putOnServers-b98 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers98.txt;'
screen -dmS putOnServers-b99 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers99.txt;'
screen -dmS putOnServers-b100 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers100.txt;'
screen -dmS putOnServers-b101 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers101.txt;'
screen -dmS putOnServers-b102 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers102.txt;'
screen -dmS putOnServers-b103 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers103.txt;'
screen -dmS putOnServers-b104 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers104.txt;'
screen -dmS putOnServers-b105 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers105.txt;'
screen -dmS putOnServers-b106 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers106.txt;'
screen -dmS putOnServers-b107 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers107.txt;'
screen -dmS putOnServers-b108 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers108.txt;'
screen -dmS putOnServers-b109 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers109.txt;'
screen -dmS putOnServers-b110 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers110.txt;'
screen -dmS putOnServers-b111 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers111.txt;'
screen -dmS putOnServers-b112 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers112.txt;'
screen -dmS putOnServers-b113 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers113.txt;'
screen -dmS putOnServers-b114 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers114.txt;'
screen -dmS putOnServers-b115 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers115.txt;'
screen -dmS putOnServers-b116 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers116.txt;'
screen -dmS putOnServers-b117 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers117.txt;'
screen -dmS putOnServers-b118 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers118.txt;'
screen -dmS putOnServers-b119 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers119.txt;'
screen -dmS putOnServers-b120 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers120.txt;'
screen -dmS putOnServers-b121 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers121.txt;'
screen -dmS putOnServers-b122 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers122.txt;'
screen -dmS putOnServers-b123 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers123.txt;'
screen -dmS putOnServers-b124 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers124.txt;'
screen -dmS putOnServers-b125 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers125.txt;'
screen -dmS putOnServers-b126 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers126.txt;'
screen -dmS putOnServers-b127 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers127.txt;'
screen -dmS putOnServers-b128 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers128.txt;'
screen -dmS putOnServers-b129 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers129.txt;'
screen -dmS putOnServers-b130 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers130.txt;'
screen -dmS putOnServers-b131 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers131.txt;'
screen -dmS putOnServers-b132 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers132.txt;'
screen -dmS putOnServers-b133 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers133.txt;'
screen -dmS putOnServers-b134 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers134.txt;'
screen -dmS putOnServers-b135 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers135.txt;'
screen -dmS putOnServers-b136 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers136.txt;'
screen -dmS putOnServers-b137 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers137.txt;'
screen -dmS putOnServers-b138 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers138.txt;'
screen -dmS putOnServers-b139 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers139.txt;'
screen -dmS putOnServers-b140 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers140.txt;'
screen -dmS putOnServers-b141 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers141.txt;'
screen -dmS putOnServers-b142 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers142.txt;'
screen -dmS putOnServers-b143 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers143.txt;'
screen -dmS putOnServers-b144 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers144.txt;'
screen -dmS putOnServers-b145 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers145.txt;'
screen -dmS putOnServers-b146 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers146.txt;'
screen -dmS putOnServers-b147 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers147.txt;'
screen -dmS putOnServers-b148 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers148.txt;'
screen -dmS putOnServers-b149 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers149.txt;'
screen -dmS putOnServers-b150 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers150.txt;'
screen -dmS putOnServers-b151 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers151.txt;'
screen -dmS putOnServers-b152 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers152.txt;'
screen -dmS putOnServers-b153 bash -c 'cd ~/vmscripts;./runOnServers.sh 1 servers/servers153.txt;'
