screen -dmS b1 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers1.txt;./runOnServers.sh 5 servers/servers1.txt;sleep 5;./runOnServers.sh 6 servers/servers1.txt; '
screen -dmS b2 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers2.txt;./runOnServers.sh 5 servers/servers2.txt;sleep 5;./runOnServers.sh 6 servers/servers2.txt; '
screen -dmS b3 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers3.txt;./runOnServers.sh 5 servers/servers3.txt;sleep 5;./runOnServers.sh 6 servers/servers3.txt; '
screen -dmS b4 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers4.txt;./runOnServers.sh 5 servers/servers4.txt;sleep 5;./runOnServers.sh 6 servers/servers4.txt; '
screen -dmS b5 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers5.txt;./runOnServers.sh 5 servers/servers5.txt;sleep 5;./runOnServers.sh 6 servers/servers5.txt; '
screen -dmS b6 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers6.txt;./runOnServers.sh 5 servers/servers6.txt;sleep 5;./runOnServers.sh 6 servers/servers6.txt; '
screen -dmS b7 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers7.txt;./runOnServers.sh 5 servers/servers7.txt;sleep 5;./runOnServers.sh 6 servers/servers7.txt; '
screen -dmS b8 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers8.txt;./runOnServers.sh 5 servers/servers8.txt;sleep 5;./runOnServers.sh 6 servers/servers8.txt; '
screen -dmS b9 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers9.txt;./runOnServers.sh 5 servers/servers9.txt;sleep 5;./runOnServers.sh 6 servers/servers9.txt; '
screen -dmS b10 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers10.txt;./runOnServers.sh 5 servers/servers10.txt;sleep 5;./runOnServers.sh 6 servers/servers10.txt; '
screen -dmS b11 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers11.txt;./runOnServers.sh 5 servers/servers11.txt;sleep 5;./runOnServers.sh 6 servers/servers11.txt; '
screen -dmS b12 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers12.txt;./runOnServers.sh 5 servers/servers12.txt;sleep 5;./runOnServers.sh 6 servers/servers12.txt; '
screen -dmS b13 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers13.txt;./runOnServers.sh 5 servers/servers13.txt;sleep 5;./runOnServers.sh 6 servers/servers13.txt; '
screen -dmS b14 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers14.txt;./runOnServers.sh 5 servers/servers14.txt;sleep 5;./runOnServers.sh 6 servers/servers14.txt; '
screen -dmS b15 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers15.txt;./runOnServers.sh 5 servers/servers15.txt;sleep 5;./runOnServers.sh 6 servers/servers15.txt; '
screen -dmS b16 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers16.txt;./runOnServers.sh 5 servers/servers16.txt;sleep 5;./runOnServers.sh 6 servers/servers16.txt; '
screen -dmS b17 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers17.txt;./runOnServers.sh 5 servers/servers17.txt;sleep 5;./runOnServers.sh 6 servers/servers17.txt; '
screen -dmS b18 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers18.txt;./runOnServers.sh 5 servers/servers18.txt;sleep 5;./runOnServers.sh 6 servers/servers18.txt; '
screen -dmS b19 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers19.txt;./runOnServers.sh 5 servers/servers19.txt;sleep 5;./runOnServers.sh 6 servers/servers19.txt; '
screen -dmS b20 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers20.txt;./runOnServers.sh 5 servers/servers20.txt;sleep 5;./runOnServers.sh 6 servers/servers20.txt; '
screen -dmS b21 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers21.txt;./runOnServers.sh 5 servers/servers21.txt;sleep 5;./runOnServers.sh 6 servers/servers21.txt; '
screen -dmS b22 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers22.txt;./runOnServers.sh 5 servers/servers22.txt;sleep 5;./runOnServers.sh 6 servers/servers22.txt; '
screen -dmS b23 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers23.txt;./runOnServers.sh 5 servers/servers23.txt;sleep 5;./runOnServers.sh 6 servers/servers23.txt; '
screen -dmS b24 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers24.txt;./runOnServers.sh 5 servers/servers24.txt;sleep 5;./runOnServers.sh 6 servers/servers24.txt; '
screen -dmS b25 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers25.txt;./runOnServers.sh 5 servers/servers25.txt;sleep 5;./runOnServers.sh 6 servers/servers25.txt; '
screen -dmS b26 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers26.txt;./runOnServers.sh 5 servers/servers26.txt;sleep 5;./runOnServers.sh 6 servers/servers26.txt; '
screen -dmS b27 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers27.txt;./runOnServers.sh 5 servers/servers27.txt;sleep 5;./runOnServers.sh 6 servers/servers27.txt; '
screen -dmS b28 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers28.txt;./runOnServers.sh 5 servers/servers28.txt;sleep 5;./runOnServers.sh 6 servers/servers28.txt; '
screen -dmS b29 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers29.txt;./runOnServers.sh 5 servers/servers29.txt;sleep 5;./runOnServers.sh 6 servers/servers29.txt; '
screen -dmS b30 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers30.txt;./runOnServers.sh 5 servers/servers30.txt;sleep 5;./runOnServers.sh 6 servers/servers30.txt; '
screen -dmS b31 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers31.txt;./runOnServers.sh 5 servers/servers31.txt;sleep 5;./runOnServers.sh 6 servers/servers31.txt; '
screen -dmS b32 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers32.txt;./runOnServers.sh 5 servers/servers32.txt;sleep 5;./runOnServers.sh 6 servers/servers32.txt; '
screen -dmS b33 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers33.txt;./runOnServers.sh 5 servers/servers33.txt;sleep 5;./runOnServers.sh 6 servers/servers33.txt; '
screen -dmS b34 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers34.txt;./runOnServers.sh 5 servers/servers34.txt;sleep 5;./runOnServers.sh 6 servers/servers34.txt; '
screen -dmS b35 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers35.txt;./runOnServers.sh 5 servers/servers35.txt;sleep 5;./runOnServers.sh 6 servers/servers35.txt; '
screen -dmS b36 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers36.txt;./runOnServers.sh 5 servers/servers36.txt;sleep 5;./runOnServers.sh 6 servers/servers36.txt; '
screen -dmS b37 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers37.txt;./runOnServers.sh 5 servers/servers37.txt;sleep 5;./runOnServers.sh 6 servers/servers37.txt; '
screen -dmS b38 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers38.txt;./runOnServers.sh 5 servers/servers38.txt;sleep 5;./runOnServers.sh 6 servers/servers38.txt; '
screen -dmS b39 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers39.txt;./runOnServers.sh 5 servers/servers39.txt;sleep 5;./runOnServers.sh 6 servers/servers39.txt; '
screen -dmS b40 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers40.txt;./runOnServers.sh 5 servers/servers40.txt;sleep 5;./runOnServers.sh 6 servers/servers40.txt; '
screen -dmS b41 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers41.txt;./runOnServers.sh 5 servers/servers41.txt;sleep 5;./runOnServers.sh 6 servers/servers41.txt; '
screen -dmS b42 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers42.txt;./runOnServers.sh 5 servers/servers42.txt;sleep 5;./runOnServers.sh 6 servers/servers42.txt; '
screen -dmS b43 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers43.txt;./runOnServers.sh 5 servers/servers43.txt;sleep 5;./runOnServers.sh 6 servers/servers43.txt; '
screen -dmS b44 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers44.txt;./runOnServers.sh 5 servers/servers44.txt;sleep 5;./runOnServers.sh 6 servers/servers44.txt; '
screen -dmS b45 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers45.txt;./runOnServers.sh 5 servers/servers45.txt;sleep 5;./runOnServers.sh 6 servers/servers45.txt; '
screen -dmS b46 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers46.txt;./runOnServers.sh 5 servers/servers46.txt;sleep 5;./runOnServers.sh 6 servers/servers46.txt; '
screen -dmS b47 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers47.txt;./runOnServers.sh 5 servers/servers47.txt;sleep 5;./runOnServers.sh 6 servers/servers47.txt; '
screen -dmS b48 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers48.txt;./runOnServers.sh 5 servers/servers48.txt;sleep 5;./runOnServers.sh 6 servers/servers48.txt; '
screen -dmS b49 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers49.txt;./runOnServers.sh 5 servers/servers49.txt;sleep 5;./runOnServers.sh 6 servers/servers49.txt; '
screen -dmS b50 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers50.txt;./runOnServers.sh 5 servers/servers50.txt;sleep 5;./runOnServers.sh 6 servers/servers50.txt; '
screen -dmS b51 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers51.txt;./runOnServers.sh 5 servers/servers51.txt;sleep 5;./runOnServers.sh 6 servers/servers51.txt; '
screen -dmS b52 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers52.txt;./runOnServers.sh 5 servers/servers52.txt;sleep 5;./runOnServers.sh 6 servers/servers52.txt; '
screen -dmS b53 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers53.txt;./runOnServers.sh 5 servers/servers53.txt;sleep 5;./runOnServers.sh 6 servers/servers53.txt; '
screen -dmS b54 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers54.txt;./runOnServers.sh 5 servers/servers54.txt;sleep 5;./runOnServers.sh 6 servers/servers54.txt; '
screen -dmS b55 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers55.txt;./runOnServers.sh 5 servers/servers55.txt;sleep 5;./runOnServers.sh 6 servers/servers55.txt; '
screen -dmS b56 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers56.txt;./runOnServers.sh 5 servers/servers56.txt;sleep 5;./runOnServers.sh 6 servers/servers56.txt; '
screen -dmS b57 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers57.txt;./runOnServers.sh 5 servers/servers57.txt;sleep 5;./runOnServers.sh 6 servers/servers57.txt; '
screen -dmS b58 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers58.txt;./runOnServers.sh 5 servers/servers58.txt;sleep 5;./runOnServers.sh 6 servers/servers58.txt; '
screen -dmS b59 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers59.txt;./runOnServers.sh 5 servers/servers59.txt;sleep 5;./runOnServers.sh 6 servers/servers59.txt; '
screen -dmS b60 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers60.txt;./runOnServers.sh 5 servers/servers60.txt;sleep 5;./runOnServers.sh 6 servers/servers60.txt; '
screen -dmS b61 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers61.txt;./runOnServers.sh 5 servers/servers61.txt;sleep 5;./runOnServers.sh 6 servers/servers61.txt; '
screen -dmS b62 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers62.txt;./runOnServers.sh 5 servers/servers62.txt;sleep 5;./runOnServers.sh 6 servers/servers62.txt; '
screen -dmS b63 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers63.txt;./runOnServers.sh 5 servers/servers63.txt;sleep 5;./runOnServers.sh 6 servers/servers63.txt; '
screen -dmS b64 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers64.txt;./runOnServers.sh 5 servers/servers64.txt;sleep 5;./runOnServers.sh 6 servers/servers64.txt; '
screen -dmS b65 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers65.txt;./runOnServers.sh 5 servers/servers65.txt;sleep 5;./runOnServers.sh 6 servers/servers65.txt; '
screen -dmS b66 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers66.txt;./runOnServers.sh 5 servers/servers66.txt;sleep 5;./runOnServers.sh 6 servers/servers66.txt; '
screen -dmS b67 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers67.txt;./runOnServers.sh 5 servers/servers67.txt;sleep 5;./runOnServers.sh 6 servers/servers67.txt; '
screen -dmS b68 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers68.txt;./runOnServers.sh 5 servers/servers68.txt;sleep 5;./runOnServers.sh 6 servers/servers68.txt; '
screen -dmS b69 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers69.txt;./runOnServers.sh 5 servers/servers69.txt;sleep 5;./runOnServers.sh 6 servers/servers69.txt; '
screen -dmS b70 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers70.txt;./runOnServers.sh 5 servers/servers70.txt;sleep 5;./runOnServers.sh 6 servers/servers70.txt; '
screen -dmS b71 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers71.txt;./runOnServers.sh 5 servers/servers71.txt;sleep 5;./runOnServers.sh 6 servers/servers71.txt; '
screen -dmS b72 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers72.txt;./runOnServers.sh 5 servers/servers72.txt;sleep 5;./runOnServers.sh 6 servers/servers72.txt; '
screen -dmS b73 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers73.txt;./runOnServers.sh 5 servers/servers73.txt;sleep 5;./runOnServers.sh 6 servers/servers73.txt; '
screen -dmS b74 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers74.txt;./runOnServers.sh 5 servers/servers74.txt;sleep 5;./runOnServers.sh 6 servers/servers74.txt; '
screen -dmS b75 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers75.txt;./runOnServers.sh 5 servers/servers75.txt;sleep 5;./runOnServers.sh 6 servers/servers75.txt; '
screen -dmS b76 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers76.txt;./runOnServers.sh 5 servers/servers76.txt;sleep 5;./runOnServers.sh 6 servers/servers76.txt; '
screen -dmS b77 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers77.txt;./runOnServers.sh 5 servers/servers77.txt;sleep 5;./runOnServers.sh 6 servers/servers77.txt; '
screen -dmS b78 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers78.txt;./runOnServers.sh 5 servers/servers78.txt;sleep 5;./runOnServers.sh 6 servers/servers78.txt; '
screen -dmS b79 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers79.txt;./runOnServers.sh 5 servers/servers79.txt;sleep 5;./runOnServers.sh 6 servers/servers79.txt; '
screen -dmS b80 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers80.txt;./runOnServers.sh 5 servers/servers80.txt;sleep 5;./runOnServers.sh 6 servers/servers80.txt; '
screen -dmS b81 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers81.txt;./runOnServers.sh 5 servers/servers81.txt;sleep 5;./runOnServers.sh 6 servers/servers81.txt; '
screen -dmS b82 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers82.txt;./runOnServers.sh 5 servers/servers82.txt;sleep 5;./runOnServers.sh 6 servers/servers82.txt; '
screen -dmS b83 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers83.txt;./runOnServers.sh 5 servers/servers83.txt;sleep 5;./runOnServers.sh 6 servers/servers83.txt; '
screen -dmS b84 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers84.txt;./runOnServers.sh 5 servers/servers84.txt;sleep 5;./runOnServers.sh 6 servers/servers84.txt; '
screen -dmS b85 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers85.txt;./runOnServers.sh 5 servers/servers85.txt;sleep 5;./runOnServers.sh 6 servers/servers85.txt; '
screen -dmS b86 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers86.txt;./runOnServers.sh 5 servers/servers86.txt;sleep 5;./runOnServers.sh 6 servers/servers86.txt; '
screen -dmS b87 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers87.txt;./runOnServers.sh 5 servers/servers87.txt;sleep 5;./runOnServers.sh 6 servers/servers87.txt; '
screen -dmS b88 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers88.txt;./runOnServers.sh 5 servers/servers88.txt;sleep 5;./runOnServers.sh 6 servers/servers88.txt; '
screen -dmS b89 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers89.txt;./runOnServers.sh 5 servers/servers89.txt;sleep 5;./runOnServers.sh 6 servers/servers89.txt; '
screen -dmS b90 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers90.txt;./runOnServers.sh 5 servers/servers90.txt;sleep 5;./runOnServers.sh 6 servers/servers90.txt; '
screen -dmS b91 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers91.txt;./runOnServers.sh 5 servers/servers91.txt;sleep 5;./runOnServers.sh 6 servers/servers91.txt; '
screen -dmS b92 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers92.txt;./runOnServers.sh 5 servers/servers92.txt;sleep 5;./runOnServers.sh 6 servers/servers92.txt; '
screen -dmS b93 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers93.txt;./runOnServers.sh 5 servers/servers93.txt;sleep 5;./runOnServers.sh 6 servers/servers93.txt; '
screen -dmS b94 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers94.txt;./runOnServers.sh 5 servers/servers94.txt;sleep 5;./runOnServers.sh 6 servers/servers94.txt; '
screen -dmS b95 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers95.txt;./runOnServers.sh 5 servers/servers95.txt;sleep 5;./runOnServers.sh 6 servers/servers95.txt; '
screen -dmS b96 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers96.txt;./runOnServers.sh 5 servers/servers96.txt;sleep 5;./runOnServers.sh 6 servers/servers96.txt; '
screen -dmS b97 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers97.txt;./runOnServers.sh 5 servers/servers97.txt;sleep 5;./runOnServers.sh 6 servers/servers97.txt; '
screen -dmS b98 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers98.txt;./runOnServers.sh 5 servers/servers98.txt;sleep 5;./runOnServers.sh 6 servers/servers98.txt; '
screen -dmS b99 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers99.txt;./runOnServers.sh 5 servers/servers99.txt;sleep 5;./runOnServers.sh 6 servers/servers99.txt; '
screen -dmS b100 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers100.txt;./runOnServers.sh 5 servers/servers100.txt;sleep 5;./runOnServers.sh 6 servers/servers100.txt; '
screen -dmS b101 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers101.txt;./runOnServers.sh 5 servers/servers101.txt;sleep 5;./runOnServers.sh 6 servers/servers101.txt; '
screen -dmS b102 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers102.txt;./runOnServers.sh 5 servers/servers102.txt;sleep 5;./runOnServers.sh 6 servers/servers102.txt; '
screen -dmS b103 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers103.txt;./runOnServers.sh 5 servers/servers103.txt;sleep 5;./runOnServers.sh 6 servers/servers103.txt; '
screen -dmS b104 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers104.txt;./runOnServers.sh 5 servers/servers104.txt;sleep 5;./runOnServers.sh 6 servers/servers104.txt; '
screen -dmS b105 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers105.txt;./runOnServers.sh 5 servers/servers105.txt;sleep 5;./runOnServers.sh 6 servers/servers105.txt; '
screen -dmS b106 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers106.txt;./runOnServers.sh 5 servers/servers106.txt;sleep 5;./runOnServers.sh 6 servers/servers106.txt; '
screen -dmS b107 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers107.txt;./runOnServers.sh 5 servers/servers107.txt;sleep 5;./runOnServers.sh 6 servers/servers107.txt; '
screen -dmS b108 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers108.txt;./runOnServers.sh 5 servers/servers108.txt;sleep 5;./runOnServers.sh 6 servers/servers108.txt; '
screen -dmS b109 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers109.txt;./runOnServers.sh 5 servers/servers109.txt;sleep 5;./runOnServers.sh 6 servers/servers109.txt; '
screen -dmS b110 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers110.txt;./runOnServers.sh 5 servers/servers110.txt;sleep 5;./runOnServers.sh 6 servers/servers110.txt; '
screen -dmS b111 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers111.txt;./runOnServers.sh 5 servers/servers111.txt;sleep 5;./runOnServers.sh 6 servers/servers111.txt; '
screen -dmS b112 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers112.txt;./runOnServers.sh 5 servers/servers112.txt;sleep 5;./runOnServers.sh 6 servers/servers112.txt; '
screen -dmS b113 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers113.txt;./runOnServers.sh 5 servers/servers113.txt;sleep 5;./runOnServers.sh 6 servers/servers113.txt; '
screen -dmS b114 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers114.txt;./runOnServers.sh 5 servers/servers114.txt;sleep 5;./runOnServers.sh 6 servers/servers114.txt; '
screen -dmS b115 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers115.txt;./runOnServers.sh 5 servers/servers115.txt;sleep 5;./runOnServers.sh 6 servers/servers115.txt; '
screen -dmS b116 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers116.txt;./runOnServers.sh 5 servers/servers116.txt;sleep 5;./runOnServers.sh 6 servers/servers116.txt; '
screen -dmS b117 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers117.txt;./runOnServers.sh 5 servers/servers117.txt;sleep 5;./runOnServers.sh 6 servers/servers117.txt; '
screen -dmS b118 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers118.txt;./runOnServers.sh 5 servers/servers118.txt;sleep 5;./runOnServers.sh 6 servers/servers118.txt; '
screen -dmS b119 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers119.txt;./runOnServers.sh 5 servers/servers119.txt;sleep 5;./runOnServers.sh 6 servers/servers119.txt; '
screen -dmS b120 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers120.txt;./runOnServers.sh 5 servers/servers120.txt;sleep 5;./runOnServers.sh 6 servers/servers120.txt; '
screen -dmS b121 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers121.txt;./runOnServers.sh 5 servers/servers121.txt;sleep 5;./runOnServers.sh 6 servers/servers121.txt; '
screen -dmS b122 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers122.txt;./runOnServers.sh 5 servers/servers122.txt;sleep 5;./runOnServers.sh 6 servers/servers122.txt; '
screen -dmS b123 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers123.txt;./runOnServers.sh 5 servers/servers123.txt;sleep 5;./runOnServers.sh 6 servers/servers123.txt; '
screen -dmS b124 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers124.txt;./runOnServers.sh 5 servers/servers124.txt;sleep 5;./runOnServers.sh 6 servers/servers124.txt; '
screen -dmS b125 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers125.txt;./runOnServers.sh 5 servers/servers125.txt;sleep 5;./runOnServers.sh 6 servers/servers125.txt; '
screen -dmS b126 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers126.txt;./runOnServers.sh 5 servers/servers126.txt;sleep 5;./runOnServers.sh 6 servers/servers126.txt; '
screen -dmS b127 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers127.txt;./runOnServers.sh 5 servers/servers127.txt;sleep 5;./runOnServers.sh 6 servers/servers127.txt; '
screen -dmS b128 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers128.txt;./runOnServers.sh 5 servers/servers128.txt;sleep 5;./runOnServers.sh 6 servers/servers128.txt; '
screen -dmS b129 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers129.txt;./runOnServers.sh 5 servers/servers129.txt;sleep 5;./runOnServers.sh 6 servers/servers129.txt;'
screen -dmS b130 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers130.txt;./runOnServers.sh 5 servers/servers130.txt;sleep 5;./runOnServers.sh 6 servers/servers130.txt;'
screen -dmS b131 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers131.txt;./runOnServers.sh 5 servers/servers131.txt;sleep 5;./runOnServers.sh 6 servers/servers131.txt;'
screen -dmS b132 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers132.txt;./runOnServers.sh 5 servers/servers132.txt;sleep 5;./runOnServers.sh 6 servers/servers132.txt;'
screen -dmS b133 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers133.txt;./runOnServers.sh 5 servers/servers133.txt;sleep 5;./runOnServers.sh 6 servers/servers133.txt;'
screen -dmS b134 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers134.txt;./runOnServers.sh 5 servers/servers134.txt;sleep 5;./runOnServers.sh 6 servers/servers134.txt;'
screen -dmS b135 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers135.txt;./runOnServers.sh 5 servers/servers135.txt;sleep 5;./runOnServers.sh 6 servers/servers135.txt;'
screen -dmS b136 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers136.txt;./runOnServers.sh 5 servers/servers136.txt;sleep 5;./runOnServers.sh 6 servers/servers136.txt;'
screen -dmS b137 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers137.txt;./runOnServers.sh 5 servers/servers137.txt;sleep 5;./runOnServers.sh 6 servers/servers137.txt;'
screen -dmS b138 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers138.txt;./runOnServers.sh 5 servers/servers138.txt;sleep 5;./runOnServers.sh 6 servers/servers138.txt;'
screen -dmS b139 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers139.txt;./runOnServers.sh 5 servers/servers139.txt;sleep 5;./runOnServers.sh 6 servers/servers139.txt;'
screen -dmS b140 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers140.txt;./runOnServers.sh 5 servers/servers140.txt;sleep 5;./runOnServers.sh 6 servers/servers140.txt;'
screen -dmS b141 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers141.txt;./runOnServers.sh 5 servers/servers141.txt;sleep 5;./runOnServers.sh 6 servers/servers141.txt;'
screen -dmS b142 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers142.txt;./runOnServers.sh 5 servers/servers142.txt;sleep 5;./runOnServers.sh 6 servers/servers142.txt;'
screen -dmS b143 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers143.txt;./runOnServers.sh 5 servers/servers143.txt;sleep 5;./runOnServers.sh 6 servers/servers143.txt;'
screen -dmS b144 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers144.txt;./runOnServers.sh 5 servers/servers144.txt;sleep 5;./runOnServers.sh 6 servers/servers144.txt;'
screen -dmS b145 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers145.txt;./runOnServers.sh 5 servers/servers145.txt;sleep 5;./runOnServers.sh 6 servers/servers145.txt;'
screen -dmS b146 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers146.txt;./runOnServers.sh 5 servers/servers146.txt;sleep 5;./runOnServers.sh 6 servers/servers146.txt;'
screen -dmS b147 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers147.txt;./runOnServers.sh 5 servers/servers147.txt;sleep 5;./runOnServers.sh 6 servers/servers147.txt;'
screen -dmS b148 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers148.txt;./runOnServers.sh 5 servers/servers148.txt;sleep 5;./runOnServers.sh 6 servers/servers148.txt;'
screen -dmS b149 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers149.txt;./runOnServers.sh 5 servers/servers149.txt;sleep 5;./runOnServers.sh 6 servers/servers149.txt;'
screen -dmS b150 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers150.txt;./runOnServers.sh 5 servers/servers150.txt;sleep 5;./runOnServers.sh 6 servers/servers150.txt;'
screen -dmS b151 bash -c 'cd ~/vmscripts;./runOnServers.sh 19 servers/servers151.txt;./runOnServers.sh 5 servers/servers151.txt;sleep 5;./runOnServers.sh 6 servers/servers151.txt;'
