screen -dmS b01 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers1.txt;"
screen -dmS b02 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers2.txt;"
screen -dmS b03 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers3.txt;"
screen -dmS b04 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers4.txt;"
screen -dmS b05 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers5.txt;"
screen -dmS b06 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers6.txt;"
screen -dmS b07 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers7.txt;"
screen -dmS b08 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers8.txt;"
screen -dmS b09 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers9.txt;"
screen -dmS b10 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers10.txt;"
screen -dmS b11 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers11.txt;"
screen -dmS b12 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers12.txt;"
screen -dmS b13 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers13.txt;"
screen -dmS b14 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers14.txt;"
screen -dmS b15 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers15.txt;"
screen -dmS b16 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers16.txt;"
screen -dmS b17 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers17.txt;"
screen -dmS b18 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers18.txt;"
screen -dmS b19 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers19.txt;"
screen -dmS b20 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers20.txt;"
screen -dmS b21 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers21.txt;"
screen -dmS b22 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers22.txt;"
screen -dmS b23 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers23.txt;"
screen -dmS b24 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers24.txt;"
screen -dmS b25 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers25.txt;"
screen -dmS b26 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers26.txt;"
screen -dmS b27 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers27.txt;"
screen -dmS b28 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers28.txt;"
screen -dmS b29 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers29.txt;"
screen -dmS b30 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers30.txt;"
screen -dmS b31 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers31.txt;"
screen -dmS b32 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers32.txt;"
screen -dmS b33 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers33.txt;"
screen -dmS b34 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers34.txt;"
screen -dmS b35 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers35.txt;"
screen -dmS b36 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers36.txt;"
screen -dmS b37 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers37.txt;"
screen -dmS b38 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers38.txt;"
screen -dmS b39 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers39.txt;"
screen -dmS b40 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers40.txt;"
screen -dmS b41 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers41.txt;"
screen -dmS b42 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers42.txt;"
screen -dmS b43 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers43.txt;"
screen -dmS b44 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers44.txt;"
screen -dmS b45 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers45.txt;"
screen -dmS b46 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers46.txt;"
screen -dmS b47 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers47.txt;"
screen -dmS b48 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers48.txt;"
screen -dmS b49 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers49.txt;"
screen -dmS b50 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers50.txt;"
screen -dmS b51 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers51.txt;"
screen -dmS b52 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers52.txt;"
screen -dmS b53 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers53.txt;"
screen -dmS b54 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers54.txt;"
screen -dmS b55 bash -c "cd ~/vmscripts;./runOnServers.sh 24 servers/servers55.txt;"
screen -dmS b56 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers56.txt;'
screen -dmS b57 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers57.txt;'
screen -dmS b58 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers58.txt;'
screen -dmS b59 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers59.txt;'
screen -dmS b60 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers60.txt;'
screen -dmS b61 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers61.txt;'
screen -dmS b62 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers62.txt;'
screen -dmS b63 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers63.txt;'
screen -dmS b64 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers64.txt;'
screen -dmS b65 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers65.txt;'
screen -dmS b66 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers66.txt;'
screen -dmS b67 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers67.txt;'
screen -dmS b68 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers68.txt;'
screen -dmS b69 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers69.txt;'
screen -dmS b70 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers70.txt;'
screen -dmS b71 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers71.txt;'
screen -dmS b72 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers72.txt;'
screen -dmS b73 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers73.txt;'
screen -dmS b74 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers74.txt;'
screen -dmS b75 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers75.txt;'
screen -dmS b76 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers76.txt;'
screen -dmS b77 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers77.txt;'
screen -dmS b78 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers78.txt;'
screen -dmS b79 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers79.txt;'
screen -dmS b80 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers80.txt;'
screen -dmS b81 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers81.txt;'
screen -dmS b82 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers82.txt;'
screen -dmS b83 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers83.txt;'
screen -dmS b84 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers84.txt;'
screen -dmS b85 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers85.txt;'
screen -dmS b86 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers86.txt;'
screen -dmS b87 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers87.txt;'
screen -dmS b88 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers88.txt;'
screen -dmS b89 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers89.txt;'
screen -dmS b90 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers90.txt;'
screen -dmS b91 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers91.txt;'
screen -dmS b92 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers92.txt;'
screen -dmS b93 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers93.txt;'
screen -dmS b94 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers94.txt;'
screen -dmS b95 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers95.txt;'
screen -dmS b96 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers96.txt;'
screen -dmS b97 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers97.txt;'
screen -dmS b98 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers98.txt;'
screen -dmS b99 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers99.txt;'
screen -dmS b100 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers100.txt;'
screen -dmS b101 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers101.txt;'
screen -dmS b102 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers102.txt;'
screen -dmS b103 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers103.txt;'
screen -dmS b104 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers104.txt;'
screen -dmS b105 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers105.txt;'
screen -dmS b106 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers106.txt;'
screen -dmS b107 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers107.txt;'
screen -dmS b108 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers108.txt;'
screen -dmS b109 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers109.txt;'
screen -dmS b110 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers110.txt;'
screen -dmS b111 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers111.txt;'
screen -dmS b112 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers112.txt;'
screen -dmS b113 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers113.txt;'
screen -dmS b114 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers114.txt;'
screen -dmS b115 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers115.txt;'
screen -dmS b116 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers116.txt;'
screen -dmS b117 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers117.txt;'
screen -dmS b118 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers118.txt;'
screen -dmS b119 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers119.txt;'
screen -dmS b120 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers120.txt;'
screen -dmS b121 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers121.txt;'
screen -dmS b122 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers122.txt;'
screen -dmS b123 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers123.txt;'
screen -dmS b124 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers124.txt;'
screen -dmS b125 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers125.txt;'
screen -dmS b126 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers126.txt;'
screen -dmS b127 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers127.txt;'
screen -dmS b128 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers128.txt;'
screen -dmS b129 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers129.txt;'
screen -dmS b130 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers130.txt;'
screen -dmS b131 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers131.txt;'
screen -dmS b132 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers132.txt;'
screen -dmS b133 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers133.txt;'
screen -dmS b134 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers134.txt;'
screen -dmS b135 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers135.txt;'
screen -dmS b136 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers136.txt;'
screen -dmS b137 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers137.txt;'
screen -dmS b138 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers138.txt;'
screen -dmS b139 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers139.txt;'
screen -dmS b140 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers140.txt;'
screen -dmS b141 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers141.txt;'
screen -dmS b142 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers142.txt;'
screen -dmS b143 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers143.txt;'
screen -dmS b144 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers144.txt;'
screen -dmS b145 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers145.txt;'
screen -dmS b146 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers146.txt;'
screen -dmS b147 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers147.txt;'
screen -dmS b148 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers148.txt;'
screen -dmS b149 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers149.txt;'
screen -dmS b150 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers150.txt;'
screen -dmS b151 bash -c 'cd ~/vmscripts;./runOnServers.sh 24 servers/servers151.txt;'
